### ISSUE TITLE
Volume data in the docker-compose.yml to not lose information

### ISSUE THREAD

**Issue by oscarvesga** [wso2/docker-ei#163]
**Description:**
When I restart the docker-compose services, I want to not lose information in EI, how I can mount the volume for that?

**Comment by oscarvesga** [comment]
Hello, I modify the docker-compose.yml file with the next code lines

```yml
version: '2.3'
services:
  wso2ei-integrator:
    image: wso2/wso2ei-integrator:6.5.0    
    volumes:
      # mounting configurations
      - ./integrator:/home/wso2carbon/wso2-config-volume/
      - ei-repository:/home/wso2carbon/wso2ei-6.5.0/repository

volumes:
  ei-repository: 
```
There is anything else folder that I have to save in a volume?
