### ISSUE TITLE
Internal server error on https://localhost:9743/dashboard/ with docker

### ISSUE THREAD

**Issue by pleymor** [wso2/docker-ei#313]
**Description:**

I'm unable to run Micro Integrator Dashboard, following the steps given here: https://wso2.com/integration/micro-integrator/install/docker/get-started/

Indeed, https://localhost:9743/dashboard/ just displays:

```json
{
	"message": "Internal server error"
}
```

And there is no error in docker logs.

**Suggested Labels:**
docker,Micro Integrator Dashboard,Internal server error

**Affected Product Version:**
4.1.0.0

**OS, DB, other environment details and versions:**
Mac OS 13.2.1 (22D68)

**Steps to reproduce:**

* With docker (as the website suggests)

```sh
# first shell
docker login docker.wso2.com
# enter email address of your wso2.com account
# enter password of your wso2.com account

docker run -it -p 8253:8253 -p 8290:8290 -p 9164:9164 docker.wso2.com/wso2mi:4.1.0.0

# 2nd shell
docker run -it -p 9443:9443 docker.wso2.com/wso2si:4.1.0.0

# 3rd shell
docker run -it -p 9743:9743 docker.wso2.com/wso2mi-dashboard:4.1.0.0
```

Open https://localhost:9743/dashboard

Pass the security alert

* With docker-compose (faster)

Create a `docker-compose.yml` file with:

```yaml
version: '3'
services:
  micro-integrator:
    image: docker.wso2.com/wso2mi:4.1.0.0
    ports:
      - "8253:8253"
      - "8290:8290"
      - "9164:9164"
  streaming-integrator:
    image: docker.wso2.com/wso2si:4.1.0.0
    ports:
      - "9443:9443"
  dashboard:
    image: docker.wso2.com/wso2mi-dashboard:4.1.0.0
    ports:
      - "9743:9743"
```

```sh
docker login docker.wso2.com
# enter email address of your wso2.com account
# enter password of your wso2.com account

docker-compose up -d
```

Open https://localhost:9743/dashboard

Pass the security alert
